// Mocks generated by Mockito 5.4.2 from annotations
// in untitled3/test/features/manufacturer_details/data/network/manufacturer_details_network_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:dio/dio.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:untitled3/core/network/request_handler.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RequestHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestHandler extends _i1.Mock implements _i3.RequestHandler {
  MockRequestHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<T> get<T>({
    required String? path,
    Map<String, dynamic>? queryParameters,
    required T Function(
      dynamic,
      _i4.Headers?,
    )? mapper,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
          {
            #path: path,
            #queryParameters: queryParameters,
            #mapper: mapper,
          },
        ),
        returnValue: _i5.ifNotNull(
              _i5.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #get,
                  [],
                  {
                    #path: path,
                    #queryParameters: queryParameters,
                    #mapper: mapper,
                  },
                ),
              ),
              (T v) => _i2.Future<T>.value(v),
            ) ??
            _FakeFuture_0<T>(
              this,
              Invocation.method(
                #get,
                [],
                {
                  #path: path,
                  #queryParameters: queryParameters,
                  #mapper: mapper,
                },
              ),
            ),
      ) as _i2.Future<T>);
}
